### PR TITLE
Fixed a bunch deprecation notices and other issues

### LINKED ISSUE #3: Clean up PHP notices, deprecation messages
Make sure scripts and styles are enqueued properly, account for undefined array indexes, ensure referenced constants have been defined, etc.

See also:
PHP Deprecated:  Non-static method DOMDocument::loadHTML() should not be called statically in Faculty-Relations-Theme/shortcodes.php on line 24

### PR DESCRIPTION
**Pull request by jmbarne3**
Bug Fixes:
* A number of php syntax changes have been made to bring the project up to date and deal with unexpected end of file errors.
* `create_function` has been removed and anonymous functions used instead.
* Lots of whitespace changes on the files that were worked on (may want to view the diff with white space changes off)
* A number of notices thrown for trying to access array indexes that don't exist have been corrected.
* Scripts and styles are not being enqueued during the appropriate WordPress hook.
* The bootstrap nav walker has been updated to have the correct parameters.

All of this should fix #3

### CODE REVIEW

File: functions/base.php [hunk 1]
```diff
@@ -828,7 +828,11 @@ function get_search_results(
 	if (strlen($query) > 0){
 		$query_string = http_build_query($arguments);
 		$url          = $search_url.'?'.$query_string;
+<<<<<<< HEAD
```
Comment (cjg89) [inline functions/base.php]: Unresolved merge conflict needs to be fixed.

**Review by cjg89 — CHANGES_REQUESTED** [review]

**Review by rjucf — APPROVED** [review]

File: functions/base.php (hunk 1 above)
Comment (jmbarne3) [reply functions/base.php]: Fixed.

**Review by cadie — APPROVED** [review]

**Review by cjg89 — APPROVED** [review]
